/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Hasan
 */
public class StartPan extends javax.swing.JFrame implements ActionListener{

    
    /**
     * Creates new form NewJFrame
     */
    private Image bg;
    private int x = 0, iniY = Game.h - 3500, y;
    public StartPan() {
        y = iniY;
        loadImg();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        //System.out.println(screen);
        Game.w = screen.width;
        Game.h = screen.height;
        initComponents();
        animate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new JPanel() {
            public void paintComponent(Graphics g) {
                customPaint(g);
            }

        };
        mainPane1 = new JPanel() {
            public void paintComponent(Graphics g) {
                customPaint(g);
            }

        };
        jLabel2 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JLabel();
        startBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Void Crysis");
        setExtendedState(6);
        setPreferredSize(new Dimension(Game.w, Game.h));
        setSize(new Dimension(Game.w, Game.h));
        setState(6);
        getContentPane().setLayout(null);

        mainPane.setBackground(new java.awt.Color(153, 153, 255));
        mainPane.setMinimumSize(new Dimension(Game.w, Game.h));
        mainPane.setPreferredSize(new Dimension(Game.w, Game.h));
        mainPane.setLayout(null);

        mainPane1.setBackground(new java.awt.Color(153, 153, 255));
        mainPane1.setMinimumSize(new Dimension(Game.w, Game.h));
        mainPane1.setPreferredSize(new Dimension(Game.w, Game.h));
        mainPane1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Void Crysis");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        mainPane1.add(jLabel2);
        jLabel2.setBounds(510, 60, 340, 140);

        exitBtn.setBackground(new java.awt.Color(44, 44, 84));
        exitBtn.setFont(new java.awt.Font("Imprint MT Shadow", 0, 48)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitBtn.setText("Exit");
        exitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        exitBtn.setOpaque(true);
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnMouseExited(evt);
            }
        });
        mainPane1.add(exitBtn);
        exitBtn.setBounds(510, 450, 340, 80);

        startBtn.setBackground(new java.awt.Color(44, 44, 84));
        startBtn.setFont(new java.awt.Font("Imprint MT Shadow", 0, 48)); // NOI18N
        startBtn.setForeground(new java.awt.Color(255, 255, 255));
        startBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startBtn.setText("Start");
        startBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        startBtn.setOpaque(true);
        startBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startBtnMouseExited(evt);
            }
        });
        mainPane1.add(startBtn);
        startBtn.setBounds(510, 290, 340, 80);

        mainPane.add(mainPane1);
        mainPane1.setBounds(0, 0, 1370, 770);

        getContentPane().add(mainPane);
        mainPane.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseEntered
        // TODO add your handling code here:
        hoverEffect(exitBtn);
    }//GEN-LAST:event_exitBtnMouseEntered

    private void exitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseExited
        // TODO add your handling code here:
        hoverEffectGone(exitBtn);
    }//GEN-LAST:event_exitBtnMouseExited

    private void startBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startBtnMouseEntered
        // TODO add your handling code here:
        hoverEffect(startBtn);
    }//GEN-LAST:event_startBtnMouseEntered

    private void startBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startBtnMouseExited
        // TODO add your handling code here:
        hoverEffectGone(startBtn);
    }//GEN-LAST:event_startBtnMouseExited

    private void startBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startBtnMouseClicked
        // TODO add your handling code here:
        Game.startGame();
        this.dispose();
    }//GEN-LAST:event_startBtnMouseClicked

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    
    void customPaint(Graphics g){
        g.drawImage(bg, x, y, null);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        makeStartPanel();
    }
    
    public static void makeStartPanel() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPan().setVisible(true);
            }
        });
    }

    
    
    void loadImg(){
         bg = new ImageIcon("images/space5.png").getImage();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emBtn;
    private javax.swing.JLabel emBtn1;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainPane;
    private javax.swing.JPanel mainPane1;
    private javax.swing.JLabel startBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        y++;
        if(y > 0){
            y = iniY;
        }
        repaint();
    }

    private void animate() {
        Timer timer = new Timer(10, this);
        timer.start();
    }
    
    private void hoverEffect(JLabel l) {
        l.setBackground(new Color(64, 64, 122)); //rgb(64, 64, 122)
        
    }

    private void hoverEffectGone(JLabel l) {
        l.setBackground(new Color(44,44,84));
    }
}
